travis:
  secure:
    BINSTAR_TOKEN: LyEX3WUF6hqyUke1ZMuCTa8q9do/gNWzNlXoMT4IO3bB71j+0AR2PtWpO/9YStNhZYPjQ7yMpuQkBxk7TW3yVmnfHv+B3EZvA19N4k3cEP/6mof9iFyQl30Vw4hIfbOUNOpzBuqBGS+BnG0mPDDkWmwwbJmv5xazXd0FuP5IUAD/t7IRqpVNXckgePEAEAx7mNUB+ry5ohKl/W83JZKbjY0hzOKlczmVsIFMwnjPP0ktJTPqwQc8ie633Nc3DaNNnkAkx/u0eEWcu8rLiWgYSG9u+OYWrBYnAkIT+FLRaz1FZgaYnzLwL8byz4Io1ccg0dnGILRhk0tkhcD4fJ2nAL/r8LEI/r7ev8xEdQg1tsVx5W9KXtXunm6DIbCYqI1Z6WnQinpPDtliOIeEX6IO9LFbpzYqDQYfMeVCQYooWbNl7qiSFopY3Ot5fdMoE5naFLkgLAQTadvSMpogcA6m7J4QJl1YDjUHlCCylXZg39Bw6z5rxMmQ2yd3eb+IjbWkubtH+rNICEMnhzNIYVmtkJeJSmXIaE8oW7TSBe3rGQ0qip2DjrZeHkKrsKcwT27EYERZC4razXvOoiOtqCMkeFLyfNM5RXr6ETHDJWJGAPCPNVryH6WjPr7+j90af990VsNCKQiHKmuyPuxsQWD+f+MS6Zrc1dl3oZTgmAzqsO8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
